version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: darasoftmain_frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks: [daranet]

  gateway:
    image: nginx:1.27-alpine
    container_name: darasoftmain_gateway
    depends_on: [frontend]
    restart: unless-stopped
    ports:
      - "80:80"                        # сайт: http://localhost
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/mime.types:/etc/nginx/mime.types:ro
    networks: [daranet]


networks:
  daranet:
    driver: bridge
