version: "3.9"

services:

  frontend:
    build:
      context: ./frontend
    container_name: darasoftmain_frontend
    restart: unless-stopped
    networks: [daranet]
    healthcheck:
        test: ["CMD-SHELL", "curl -Lfs -o /dev/null http://127.0.0.1:3001 || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 10

  gateway:
    image: nginx:1.27-alpine
    container_name: darasoftmain_gateway
    depends_on:
      frontend:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/mime.types:/etc/nginx/mime.types:ro
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      # Серты внутрь контейнера
      - /opt/darasoft/certs:/etc/nginx/certs:ro
    networks: [daranet]

networks:
  daranet:
    driver: bridge
